# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: videoproc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'videoproc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvideoproc.proto\x12\tvideoproc\">\n\nVideoChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08video_id\x18\x03 \x01(\t\"S\n\x0fProcessResponse\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t2U\n\x0eVideoProcessor\x12\x43\n\x0cProcessVideo\x12\x15.videoproc.VideoChunk\x1a\x1a.videoproc.ProcessResponse(\x01\x42\x1bZ\x19proto/videoproc;videoprocb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'videoproc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031proto/videoproc;videoproc'
  _globals['_VIDEOCHUNK']._serialized_start=30
  _globals['_VIDEOCHUNK']._serialized_end=92
  _globals['_PROCESSRESPONSE']._serialized_start=94
  _globals['_PROCESSRESPONSE']._serialized_end=177
  _globals['_VIDEOPROCESSOR']._serialized_start=179
  _globals['_VIDEOPROCESSOR']._serialized_end=264
# @@protoc_insertion_point(module_scope)
