// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: videoproc.proto

package videoproc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoChunk) Reset() {
	*x = VideoChunk{}
	mi := &file_videoproc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChunk) ProtoMessage() {}

func (x *VideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_videoproc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChunk.ProtoReflect.Descriptor instead.
func (*VideoChunk) Descriptor() ([]byte, []int) {
	return file_videoproc_proto_rawDescGZIP(), []int{0}
}

func (x *VideoChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *VideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoChunk) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_videoproc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_videoproc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_videoproc_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ProcessResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProcessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_videoproc_proto protoreflect.FileDescriptor

const file_videoproc_proto_rawDesc = "" +
	"\n" +
	"\x0fvideoproc.proto\x12\tvideoproc\"W\n" +
	"\n" +
	"VideoChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\"t\n" +
	"\x0fProcessResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2U\n" +
	"\x0eVideoProcessor\x12C\n" +
	"\fProcessVideo\x12\x15.videoproc.VideoChunk\x1a\x1a.videoproc.ProcessResponse(\x01B\x1bZ\x19proto/videoproc;videoprocb\x06proto3"

var (
	file_videoproc_proto_rawDescOnce sync.Once
	file_videoproc_proto_rawDescData []byte
)

func file_videoproc_proto_rawDescGZIP() []byte {
	file_videoproc_proto_rawDescOnce.Do(func() {
		file_videoproc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_videoproc_proto_rawDesc), len(file_videoproc_proto_rawDesc)))
	})
	return file_videoproc_proto_rawDescData
}

var file_videoproc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_videoproc_proto_goTypes = []any{
	(*VideoChunk)(nil),      // 0: videoproc.VideoChunk
	(*ProcessResponse)(nil), // 1: videoproc.ProcessResponse
}
var file_videoproc_proto_depIdxs = []int32{
	0, // 0: videoproc.VideoProcessor.ProcessVideo:input_type -> videoproc.VideoChunk
	1, // 1: videoproc.VideoProcessor.ProcessVideo:output_type -> videoproc.ProcessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_videoproc_proto_init() }
func file_videoproc_proto_init() {
	if File_videoproc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_videoproc_proto_rawDesc), len(file_videoproc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_videoproc_proto_goTypes,
		DependencyIndexes: file_videoproc_proto_depIdxs,
		MessageInfos:      file_videoproc_proto_msgTypes,
	}.Build()
	File_videoproc_proto = out.File
	file_videoproc_proto_goTypes = nil
	file_videoproc_proto_depIdxs = nil
}
